name: Build and Deploy Agent

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Package agent
        run: make package

      - name: Register agent in MLflow
        run: make register

      - name: Deploy agent
        run: make deploy

      - name: Cleanup
        run: make clean
